### ISSUE TITLE
Provided .clang-format file does not work with ament_cmake_clang_format

### ISSUE THREAD

**Issue by pucciland95** [davetcoleman/roscpp_code_format#17]
Hi, 

I am trying to use your .config-clang file when I issue `colcon test` from a VsCode Task. 
My `CMakeList.txt`:
``` cmake
if(BUILD_TESTING)
  set(ament_cmake_clang_format_CONFIG_FILE "my_path_to.clang-format")
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
endif()
```

My `package.xml`:
``` xml
<test_depend>ament_lint_auto</test_depend>
<test_depend>ament_cmake_clang_format</test_depend>
```
After building the ROS2 workspace and launching:
``` bash 
colcon test --event-handlers console_direct+ --packages-select my_beautiful_pkg_name
```
the command outputs:
``` bash
Traceback (most recent call last):               
1:   File "/opt/ros/humble/bin/ament_clang_format", line 33, in <module>
1:     sys.exit(load_entry_point('ament-clang-format==0.12.11', 'console_scripts', 'ament_clang_format')())
1:   File "/opt/ros/humble/lib/python3.10/site-packages/ament_clang_format/main.py", line 101, in main
1:     data = yaml.safe_load(content)
1:   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
1:     return load(stream, SafeLoader)
1:   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
1:     return loader.get_single_data()
1:   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
1:     node = self.get_single_node()
1:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
1:     document = self.compose_document()
1:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
1:     node = self.compose_node(None, None)
1:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
1:     node = self.compose_mapping_node(anchor)
1:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
1:     item_value = self.compose_node(node, item_key)
1:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
1:     node = self.compose_mapping_node(anchor)
1:   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
1:     while not self.check_event(MappingEndEvent):
1:   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
1:     self.current_event = self.state()
1:   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 549, in parse_flow_mapping_key
1:     raise ParserError("while parsing a flow mapping", self.marks[-1],
1: yaml.parser.ParserError: while parsing a flow mapping
1:   in "<unicode string>", line 51, column 16:
1:     BraceWrapping: {
1:                    ^
1: expected ',' or '}', but got '<scalar>'
1:   in "<unicode string>", line 53, column 5:
1:         AfterControlStatement: 'true'
1:         ^
```
It seems that the .config-clang file is **incorrect**.

Indeed, changing this:

``` yaml
BraceWrapping:{
    AfterClass: 'true'
    AfterControlStatement: 'true'
    AfterEnum : 'true'
    AfterFunction : 'true'
    AfterNamespace : 'true'
    AfterStruct : 'true'
    AfterUnion : 'true'
    BeforeCatch : 'true'
    BeforeElse : 'true'
    IndentBraces : 'false'
}
```
to this:

``` yaml
BraceWrapping:
    AfterClass: 'true'
    AfterControlStatement: 'true'
    AfterEnum : 'true'
    AfterFunction : 'true'
    AfterNamespace : 'true'
    AfterStruct : 'true'
    AfterUnion : 'true'
    BeforeCatch : 'true'
    BeforeElse : 'true'
    IndentBraces : 'false'
```

or this:
``` yaml
BraceWrapping: {
    AfterClass: 'true',
    AfterControlStatement: 'true',
    AfterEnum : 'true',
    AfterFunction : 'true',
    AfterNamespace : 'true',
    AfterStruct : 'true',
    AfterUnion : 'true',
    BeforeCatch : 'true',
    BeforeElse : 'true',
    IndentBraces : 'false'
}
```
does not issue any error and the test runs correctly.

However, using the original `.clang-format` with the clang-format command or in Vs Code does not create any error.  
As far as I understand, `ament_cmake_clang_format` uses `ament_clang_format`, but I have no idea if they are actually the same thing, and the internet is of no help. 
Am I doing something wrong? Am I using your file in a way it is not supposed to?

Cheers and thank you in advance,

EDIT: it seems like `ament_cmake_clang_format` uses the YAML Python pkg to read a custom .config file, and the original file does not have a correct syntax.

EDIT2: I just noticed a PR #16 about this. Furthermore, in this video you guys made: https://www.youtube.com/watch?v=4K6GZWFQs3A at the minute 6:20 you fix the error. I will close the issue since there is already a pending PR and the problem is actually in the YAML file.

Niccolo
